### ISSUE TITLE
cv_bridge dependency error

### ISSUE THREAD

**Issue by ivoysey** [cmu-mars/ros1-to-ros2-sandbox#4]
I saw this flash by towards the end of building the container; is this something that you've seen before and fixed, or something I should worry about?

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cv_bridge: Cannot locate rosdep definition for [opencv3]
```

I'm used to ignoring a ton of warnings from ROS, but outright errors aren't as easy to blow off.

**Comment by audreyseo** [comment]
I'm not sure if I "fixed" this, per se. The opencv3 package is not available for any ROS distributions after kinetic, so neither melodic nor bouncy has one pre-built. I could potentially build opencv3 from source, but I'm not sure if that would improve the fact that rosdep doesn't have a definition for opencv3.

I've attempted to just try to build everything in kinetic instead, but the Docker image for `ros:kinetic` uses Ubuntu Xenial, which happens to use python 3.5 which breaks colcon build (see #5).

This particular error used to halt installation, but I added the flag `-r` to the `rosdep install` command. I'm attempting to see if installing opencv3 is actually feasible without breaking everything else completely, like changing to kinetic seems to.

**Comment by audreyseo** [comment]
I'm also not sure though how effective it would be though to try to install opencv3 if I can't make rosdep see that it's already on the system?
(Opencv3 also takes a very long time to build.)

**Comment by audreyseo** [comment]
I tried building opencv3, and this also didn't get rid of the error, although I'm not sure if it will affect how the code actually runs. I'm not sure how vital computer vision (cv) is to how turtlebot2_demo runs, and at this stage, it seems unlikely that I'd be running this code.
