### ISSUE TITLE
Constantly running out of space for docker images

### ISSUE THREAD

**Issue by audreyseo** [cmu-mars/ros1-to-ros2-sandbox#6]
Interestingly, my computer isn't complaining about being low on storage at all, but docker is constantly running out of space for docker images and so that halts the build.

It may just be the space allotted to each container or something?

(I feel like conceptually the docker containers are a little bit fuzzy too.)

**Comment by audreyseo** [comment]
Apparently if you go to Preferences > Advanced (for Docker Desktop) you can change the amount of storage you give to Docker as well as how much memory you allot it. I changed it to 4 GiB of memory from 2, so we'll see if that does anything...

**Comment by ivoysey** [comment]
you may also be running out of disk space, or hitting a docker limit for how much disk space it's willing to actually use. i have this script in my $PATH and run it occasionally; it's _quite_ destructive and just nukes every intermediate container and image, which is fine except it means you have to rebuild at least whatever you're working on:
```
#!/bin/bash
# delete all docker containers
docker rm $(docker ps -a -q)

# delete all images
docker rmi $(docker images -q)
```
you can do `docker images` or `docker ps` to see the lists before deleting them
